config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "quests#index"
  resources :quests do
    collection do
      get 'yet_list'
      get 'doing_list'
      get 'success_list'
    end
    resources :successes, only: [:index,:new,:create]
    resources :faileds,  only: [:index,:new,:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    # 直面課題
    { id: 2, name: 'フロントクエスト' },
    # 問題解決
    { id: 3, name: 'トラブルクエスト' },
    # 夢の実現
    { id: 4, name: 'ドリームクエスト' },
    # 自己成長
    { id: 5, name: 'トレーニングクエスト' },
    # 例外
    { id: 6, name: 'エクセプションクエスト' },
  ]  

  include ActiveHash::Associations
  has_many :quests

end

app/models/checker.rb
class Checker < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '作成のみ' },
    { id: 3, name: '受注'},
  ]  

  include ActiveHash::Associations
  has_many :quest_success_results
  has_many :quest_failed_results

end

app/models/failed.rb
class Failed < ApplicationRecord
  belongs_to :user
  belongs_to :quest

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :failed_reason

  with_options numericality: { other_than: 1 } do
    validates :failed_reason_id
  end

  with_options presence: true do
    validates :failed_reason_id,:user,:quest
  end
end

app/models/failed_reason.rb
class FailedReason < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    # 期限切れ
    { id: 2, name: '期限切れ' },
    # 仕切り直し
    { id: 3, name: '予定変更' },
    # 想定外の事態
    { id: 4, name: '状況の変化' },
    # モチベーション
    { id: 5, name: 'やる気切れ' },
  ]  

  include ActiveHash::Associations
  has_many :faileds

end

app/models/quest.rb
class Quest < ApplicationRecord

  belongs_to :user
  has_one_attached :image
  has_one :success
  has_one :failed

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :checker

  with_options presence: true do
    validates :category_id,:title,:explain,:limit,:user
  end

  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :checker_id
  end

  validate :date_before_start

  def date_before_start
    if limit <= Date.today && limit_time.blank?
      errors.add(:limit, "-- 期限は今日以降のものを選択してください")
    elsif limit == Date.today && limit_time < Time.now.to_s
      errors.add(:limit, "-- 当日中の期限は、現在時刻以降のものを選択してください")
    end
  end

end

app/models/quest_failed_result.rb
class QuestFailedResult < ApplicationRecord
  with_options numericality: { equal_to: 3 } do
    validates :second_checker_id
  end
  belongs_to :second_checker
end

app/models/quest_success_result.rb
class QuestSuccessResult < ApplicationRecord
  with_options numericality: { equal_to: 2 } do
    validates :second_checker_id
  end
  belongs_to :second_checker
end

app/models/success.rb
class Success < ApplicationRecord
  belongs_to :user
  belongs_to :quest

  with_options presence: true do
    validates :user,:quest
  end

  validate :success_limit_check

  # def success_limit_check
  #   if limit < Date.today
  #     errors.add(:limit, "-- 期限が切れています。失敗での登録をお願いします。")
  #   elsif limit = Date.today && limit_time < Time.now.to_s
  #     errors.add(:limit, "-- 期限が切れています。失敗での登録をお願いします。")
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :quests

  with_options presence: true do
    validates :nickname
    validates :password,           format: {with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]{6,}/}
    validates :last_name,        format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: '全角文字を使用してください' }
    validates :first_name,          format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: '全角文字を使用してください' }
    validates :kana_last_name,   format: { with:/\A[ァ-ヶー－]+\z/, message: '全角カタカナを使用してください'}
    validates :kana_first_name,     format: { with:/\A[ァ-ヶー－]+\z/, message: '全角カタカナを使用してください'}
    validates :birth
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :last_name, :first_name, :kana_last_name, :kana_first_name, :birth])
  end
end

app/controllers/faileds_controller.rb
class FailedsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_params, only: [:index,:new,:create]

  def index
  end

  def new
    @failed = Failed.new
  end

  def create
    @failed = Failed.new(failed_params)
    if @failed.save
      redirect_to root_path, notice: "クエスト 『 #{@quest.title} 』 が失敗しました……"
    else
      render :new
    end
  end

  private
  def set_params
    @quest = Quest.find(params[:quest_id])
  end

  def failed_params
    params.require(:failed).permit(:failed_reason_id,:reason).merge(user_id: current_user.id,quest_id: params[:quest_id])
  end

end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  # インデックスはログインしていない場合の表示があるので除外
  before_action :authenticate_user!, except: :index
  before_action :set_params, only: [:show,:edit,:update,:destroy]
  before_action :check, only: [:edit,:destroy]
  before_action :list_params, only: [:yet_list,:doing_list,:success_list]

  def index
    @quests = Quest.all.order("created_at DESC")
  end

  def new
    @quest = Quest.new
  end

  def create
    @quest = Quest.new(quest_params)
    if @quest.save
      redirect_to root_path, notice: "クエスト 『 #{@quest.title} 』 を登録しました！"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def yet_list
  end

  def doing_list
  end

  def success_list
  end

  def update
    if @quest.update(quest_params)
      flash[:notice] = "クエスト『#{@quest.title}』が変更されました"
        redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = "クエスト『#{@quest.title}』が削除されました"
    @quest.destroy
    redirect_to root_path
  end

  private

  def quest_params
    params.require(:quest).permit(:image,:category_id,:title,:explain,:limit,:limit_time,:achievement_purpose,:achievement_condition,
      :self_reward,:self_penalty,:order_condition,:detail_text,:user,:checker_id).merge(user_id: current_user.id)
  end

  def set_params
    @quest = Quest.find(params[:id])
  end

  def list_params
    @quests = Quest.all.order("created_at DESC")
  end

  def check
    if current_user.id != @quest.user_id
      redirect_to root_path
    end
  end

end

app/controllers/successes_controller.rb
class SuccessesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_params, only: [:index,:new,:create]

  def index
  end

  def new
    @success = Success.new
  end

  def create
    @success = Success.new(success_params)
    if @success.save
      redirect_to root_path, notice: "おめでとうございます！ クエスト 『 #{@quest.title} 』を達成しました！！"
    else
      render :new
    end
  end

  private
  def set_params
    @quest = Quest.find(params[:quest_id])
  end

  def success_params
    params.require(:success).permit(:reason).merge(user_id: current_user.id,quest_id: params[:quest_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faileds_helper.rb
module FailedsHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/successes_helper.rb
module SuccessesHelper
end

app/views/faileds/new.html.erb
失敗
<div class="failed-form">
  <div class="failed-data">
    <div><%= @quest.title%></div>
    <div><%= @quest.limit%></div>
  </div>

    <%= form_with  model: @failed,url: quest_faileds_path, local: true do |f| %>
      <div class="failed-field">
        <%= f.collection_select(:failed_reason_id, FailedReason.all, :id, :name, {}, {class:"failed-box", id:"quest-checker"})%>
        <div class="weight-bold-text">備考</div>
        <%= f.text_area :reason, class:"reason-text", id:"reasons-name", placeholder:"後で見返す用に、必要であれば利用してください(400文字)。",maxlength:"400" %>
        <%= f.submit "決定する" , class:"failed-btn" %>
        <%= link_to 'もどる', '/', class: "back-btn"%>
      </div>
    <% end %>

</div>

app/views/quests/choosed_list.html.erb
<%= render "shared/header" %>
<div class="choosed-top">
  一覧表示
</div>
<div class='choosed-quest-contents'>
  <ul class='choosed-quest-lists'>
    <% @quests.each do |quest| %>
      <%# 本人のクエストのみ表示 %>
      <% if current_user.id == quest.user_id %>
        <%= link_to quest_path(quest.id)  do%>
          <% if quest.checker_id == 1 %>
            <div class='choosed-quest-content'>
              <h5 class='quest-category'>
                <%= quest.category.name%>
              </h5>
              <h3 class='quest-title'>
                <%= quest.title %>
              </h3>
              <% if quest.image.present? %>
                <%= image_tag quest.image, class: "quest-image" %>
              <% else %>
                <%= image_tag "no-image.png",class:"quest-image"%>
              <% end %>
              <h4 class='quest-explain'>
                <%= quest.explain %>
              </h4>
              <h5 class='quest-limit'>
                期限：<%= quest.limit %> 
                <% if quest.limit_time.present? %>時刻: <%= quest.limit_time%><% end %>
              </h5>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <%# 本人のクエストのみ表示 %>
    <% end%>
  </ul>
</div>
<div class="choosed-bottom">
  <%= link_to "戻る", "/",class:"choosed-back"%>
</div>
<%= render "shared/footer"%>

app/views/quests/doing_list.html.erb
<%= render "shared/header" %>
<div class="yet-top">
  <p>進行中クエスト一覧</p>
</div>
<div class='yet-quest-contents'>
  <ul class='yet-quest-lists'>
    <% @quests.each do |quest| %>
      <%# 本人のクエストのみ表示 %>
      <% if quest.success.blank? && quest.failed.blank? && current_user.id == quest.user_id && quest.checker_id == 3 %>
        <%= link_to quest_path(quest.id)  do%>
          <div class='yet-quest-content'>
            <h5 class='quest-category'>
              <%= quest.category.name%>
            </h5>
            <h3 class='quest-title'>
              <%= quest.title %>
            </h3>
            <% if quest.image.present? %>
              <%= image_tag quest.image, class: "quest-image" %>
            <% else %>
              <%= image_tag "no-image.png",class:"quest-image"%>
            <% end %>
            <h4 class='quest-explain'>
              <%= quest.explain %>
            </h4>
            <h5 class='quest-limit'>
              期限：<%= quest.limit %> 
              <% if quest.limit_time.present? %>時刻: <%= quest.limit_time%><% end %>
            </h5>
          </div>
        <% end %>
      <% end %>
      <%# 本人のクエストのみ表示 %>
    <% end%>
  </ul>
</div>
<div class="yet-bottom">
  <%= link_to "戻る", "/",class:"yet-back"%>
</div>
<%= render "shared/footer"%>

app/views/quests/edit.html.erb
<div class="new-quest-contents">
  <header class="my-quest-header">
    <%= link_to image_tag("logo.png", class:"quest-icon"), root_path %>
  </header>
  <div class="new-quest-main">
    <h2 class="new-quest-title">クエストの情報を入力</h2>
    <%= form_with  model: @quest, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        参考画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"quest-image" %>
      </div>
    </div>
    <div id="image-view"></div>
    <%# /出品画像 %>

    <%# クエスト名と説明 %>
    <div class="new-quests">
      <div class="weight-bold-text">
        クエスト名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"quests-text", id:"quest-name", placeholder:"クエスト名を入れてください(40字以内)。同じ名前は避けた方が望ましいです。", maxlength:"40" %>
      <div class="quests-explain">
        <div class="weight-bold-text">
          サブタイトル（クエスト説明を完結に）
          <span class="indispensable">必須<span>
        </div>
        <%= f.text_area :explain, class:"quests-text", id:"quest-info", placeholder:"クエストの説明を簡潔に（100字以内）。一目でどのようなものなのかが分かる説明がいいです。" ,rows:"3" ,maxlength:"100" %>
      </div>
      <div class="weight-bold-text">受注条件</div>
      <div class="weight-bold-text">
        期限
        <span class="indispensable">必須</span>
      </div>
      <%= f.date_field :limit, class:'date-select'%>
      <div class="weight-bold-text">
        時刻
      </div>
      <%= f.time_field :limit_time, class:'time-select'%>
    </div>
    <%# /クエスト名と説明 %>

    <%# クエストの詳細 %>
    <div class="quests-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"quest-category"}) %>
        <div class="weight-bold-text">達成目的</div>
        <%= f.text_area :achievement_purpose, class:"quests-text", id:"quest-info", placeholder:"何のためにクエストに臨むのかを簡潔に（100字以内）。一目でどのようなものなのかが分かる説明がいいです。" ,rows:"3" ,maxlength:"100" %>
        <div class="weight-bold-text">達成条件</div>
        <%= f.text_area :achievement_condition, class:"quests-text", id:"quest-info", placeholder:"どうすれば達成したことになるのかを簡潔に(100字以内)書きましょう。",rows:"3",maxlength:"100"%>
        <div class="weight-bold-text">自分への達成報酬</div>
        <%= f.text_area :self_reward, class:"quests-text", id:"quest-info", placeholder:"達成した際に何が得られるのかを簡潔に(100字以内)書きましょう。自分へのご褒美なので、現実的なもののほうがいいでしょう。",rows:"3",maxlength:"100"%>
        <div class="weight-bold-text">失敗ペナルティ</div>
        <%= f.text_area :self_penalty, class:"quests-text", id:"quest-info", placeholder:"失敗したらどうなるのかを簡潔に(100字以内)書きましょう。自分で設定するものなので、同じく現実的なものにしましょう。",rows:"3",maxlength:"100"%>
        <div class="weight-bold-text">詳細説明</div>
        <%= f.text_area :detail_text, class:"quests-text", id:"quest-info", placeholder:"詳細な説明を書きましょう(400字以内)。ストーリー性があるものでもいいですが、公開する場合には個人が特定されないように注意してください。",rows:"7",maxlength:"400"%>
        <div class="weight-bold-text">達成状況(今すぐ受けるか、後で受けるのかを選んでください。)</div>
        <%= f.collection_select(:checker_id, Checker.all, :id, :name, {}, {class:"select-box", id:"quest-checker"})%>
      </div>
    </div>
    <%# /クエストの詳細 %>

    <%# 下部ボタン %>
    <div class="create-btn-contents">
      <%= f.submit "変更する" , class:"create-btn" %>
      <%=link_to 'もどる', quest_path(@quest.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/quests/show.html.erb
<div class="show-all">
  <div class='show-quest-content'>
    <div class='show-quest-category'>
      <% if @quest.category_id == 2 %>
        ＜<span class="show-category-name1">
      <% elsif @quest.category_id == 3 %>
        ＜<span class="show-category-name2">
      <% elsif @quest.category_id == 4 %>
        ＜<span class="show-category-name3">
      <% elsif @quest.category_id == 5 %>
        ＜<span class="show-category-name4">
      <% elsif @quest.category_id == 6 %>
        ＜<span class="show-category-name5">
      <% end %>
      <%= @quest.category.name%></span>＞
    </div>
    <div class='show-quest-title'>
      <% if @quest.category_id == 2 %>
        <span class='show-title-effect1'>
      <% elsif @quest.category_id == 3 %>
        <span class='show-title-effect2'>
      <% elsif @quest.category_id == 4 %>
        <span class='show-title-effect3'>
      <% elsif @quest.category_id == 5 %>
        <span class='show-title-effect4'>
      <% elsif @quest.category_id == 6 %>
        <span class='show-title-effect5'>
      <% end %>
      『<%= @quest.title %>』</span>
    </div>
    <% if @quest.image.present? %>
      <%= image_tag @quest.image, class: "show-quest-image" %>
    <% else %>
      <%= image_tag "no-image.png", class: "show-quest-image" %>
    <% end %>
    <div class='show-quest-explain'>
      達成要件 ：<%= @quest.explain %>
    </div>
    <div class='show-quest-limit'>
      期限：<%= @quest.limit %>
      <% if @quest.limit_time.present? %>
        時刻: <%= @quest.limit_time%>
      <% end %>
    </div>
  </div>
  <div class="show-quests-detail">
    ・達成目的      ：<%= @quest.achievement_purpose %><br>
    ・達成条件      ：<%= @quest.achievement_condition %><br>
    ・達成報酬      ：<%= @quest.self_reward %><br>
    ・失敗ペナルティ ：<%= @quest.self_penalty %><br>
    ・依頼状態      ：<%= @quest.checker.name%><br>
    <div class="note-wrap">
      <div class="note">
        ・クエスト内容   ：<br>
        <p>
          <%= @quest.detail_text %>
        </p>
      </div>
    </div>
  </div>
  <div class="show-btns">
    <%= link_to 'もどる', '/', class: "show-btn"%>
    <% if @quest.checker_id == 2 %>
      <%= link_to '編集する', edit_quest_path, class: "show-btn"%>
      <%= link_to "削除", quest_path, method: :delete, class:"destroy-btn", data: {confirm: "削除しますか？"}  %>
    <% end %>
  </div>
  <% if @quest.checker_id == 3 && @quest.success.blank? %>
    <div class="shift-btns">
      <%= link_to '達成登録', new_quest_success_path(@quest.id),class: "shift-btn"%>
      <%= link_to '失敗登録', new_quest_failed_path(@quest.id),class: "shift-btn"%>
    </div>
  <% end %>
</div>

app/views/quests/success_list.html.erb
<%= render "shared/header" %>
<div class="yet-top">
  <p>進行中クエスト一覧</p>
</div>
<div class='yet-quest-contents'>
  <ul class='yet-quest-lists'>
    <% @quests.each do |quest| %>
      <%# 本人のクエストのみ表示 %>
      <% if quest.success.present? && quest.failed.blank? && current_user.id == quest.user_id && quest.checker_id == 3 %>
        <%= link_to quest_path(quest.id)  do%>
          <div class='yet-quest-content'>
            <h5 class='quest-category'>
              <%= quest.category.name%>
            </h5>
            <h3 class='quest-title'>
              <%= quest.title %>
            </h3>
            <% if quest.image.present? %>
              <%= image_tag quest.image, class: "quest-image" %>
            <% else %>
              <%= image_tag "no-image.png",class:"quest-image"%>
            <% end %>
            <h4 class='quest-explain'>
              <%= quest.explain %>
            </h4>
            <h5 class='quest-limit'>
              期限：<%= quest.limit %> 
              <% if quest.limit_time.present? %>時刻: <%= quest.limit_time%><% end %>
            </h5>
          </div>
        <% end %>
      <% end %>
      <%# 本人のクエストのみ表示 %>
    <% end%>
  </ul>
</div>
<div class="yet-bottom">
  <%= link_to "戻る", "/",class:"yet-back"%>
</div>
<%= render "shared/footer"%>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_user-room.html.erb
<div class="user-home-text1">
  <h2 class="user-room-name"><%= current_user.nickname%>さんの部屋です。</h2>
  <% if flash[:notice] %>
      <p class="accept-log"><%= flash[:notice] %></p>
  <% else %>
      <p class="accept-log">クエストに対する変更が表示されます。</p>
  <% end %>
  <div class="create-quest-btn">
    <%= link_to '＊ クエスト作成 ＊', new_quest_path, class: "create-quest" %>
  </div>
  <ul class="quest-board">
    <div class="list__wrapper">
      <div class='list'>
        <li>
          <div class="list-name">
            <%= link_to '未受注クエスト',  yet_list_quests_path %>
          </div>
          <ul class='quest-lists'>
            <% @quests.each do |quest| %>
              <%# 本人のクエストのみ表示 %>
              <% if current_user.id == quest.user_id && quest.checker_id == 2 && quest.success.blank? && quest.failed.blank? %>
                <%= link_to quest_path(quest.id)  do%>
                  <div class='quest-content'>
                    <h5 class='quest-category'>
                      <%= quest.category.name%>
                    </h5>
                    <h3 class='quest-title'>
                      <%= quest.title %>
                    </h3>
                    <% if quest.image.present? %>
                      <%= image_tag quest.image, class: "quest-image" %>
                    <% else %>
                      <%= image_tag "no-image.png",class:"quest-image"%>
                    <% end %>
                    <h4 class='quest-explain'>
                      <%= quest.explain %>
                    </h4>
                    <h5 class='quest-limit'>
                      期限：<%= quest.limit %> 
                      <% if quest.limit_time.present? %>時刻: <%= quest.limit_time%><% end %>
                    </h5>
                  </div>
                <% end %>
              <% end %>
              <%# 本人のクエストのみ表示 %>
            <% end%>
          </ul>
        </li>
      </div>
      <div class='list'>
        <li>
          <div class="list-name">
            <%= link_to '進行中クエスト', doing_list_quests_path %>
          </div>
          <%# checker.idの値によって表示変更 %>
          <div class='quest-contents'>
            <ul class='quest-lists'>
              <% @quests.each do |quest| %>
                <%# 本人のクエストのみ表示 %>
                <% if current_user.id == quest.user_id && quest.success.blank? && quest.failed.blank? && quest.checker_id == 3 %>
                  <%= link_to quest_path(quest)  do%>
                    <div class='quest-content'>
                      <h5 class='quest-category'>
                        <%= quest.category.name%>
                      </h5>
                      <h3 class='quest-title'>
                        <%= quest.title %>
                      </h3>
                      <% if quest.image.present? %>
                        <%= image_tag quest.image, class: "quest-image" %>
                      <% else %>
                        <%= image_tag "no-image.png",class:"quest-image"%>
                      <% end %>
                      <h4 class='quest-explain'>
                        <%= quest.explain %>
                      </h4>
                      <h5 class='quest-limit'>
                        期限：<%= quest.limit %> 時刻: <%= quest.limit_time%>
                      </h5>
                    </div>
                  <% end %>
                <% end %>
                <%# /本人のクエストのみ表示 %>
              <% end%>
            </ul>
          </div>
        </li>
        <%# /checker.idの値によって表示変化 %>
      </div>
      <div class='list'>
        <li>
          <div class="list-name">
            <%= link_to '達成済みクエスト', success_list_quests_path %>
          </div>
          <div class='quest-contents'>
            <ul class='quest-lists'>
              <% @quests.each do |quest| %>
                <%# 本人のクエストのみ表示 %>
                <% if quest.success.present? && quest.failed.blank? && current_user.id == quest.user_id && quest.checker_id == 3 %>
                  <%= link_to quest_path(quest)  do%>
                    <div class='quest-content'>
                      <h5 class='quest-category'>
                        <%= quest.category.name%>
                      </h5>
                      <h3 class='quest-title'>
                        <%= quest.title %>
                      </h3>
                      <% if quest.image.present? %>
                        <%= image_tag quest.image, class: "quest-image" %>
                      <% else %>
                        <%= image_tag "no-image.png",class:"quest-image"%>
                      <% end %>
                      <h4 class='quest-explain'>
                        <%= quest.explain %>
                      </h4>
                      <h5 class='quest-limit'>
                        期限：<%= quest.limit %> 時刻: <%= quest.limit_time%>
                      </h5>
                    </div>
                  <% end %>
                <% end %>
                <%# /本人のクエストのみ表示 %>
              <% end%>
            </ul>
          </div>
        </li>
      </div>
      <div class='list'>
        <li>
          <div class="list-name">
            <%= link_to 'クエストログ(仮)', '#'%>
          </div>
          <%# <%= Time.zone.now.to_s(:datetime_jp) %>
          未実装
          <% @quests.each do |quest| %>
            <div><%= quest.created_at.to_s(:datetime_jp) %></div>
            <div>『<%= quest.title %>』作成</div>
            <% if quest.created_at != quest.updated_at %>
              <div><%= quest.updated_at.to_s(:datetime_jp) %></div>
              <div>『<%= quest.title %>』変更</div>
            <% elsif quest.success.present? &&  %>
              <div><%= quest.success.created_at.to_s(:datetime_jp) %></div>
              <div>『<%= quest.title %>』達成</div>
            <% elsif quest.failed.present? %>
              <div><%= quest.failed.created_at.to_s(:datetime_jp) %></div>
              <div>『<%= quest.title %>』失敗</div>
            <% end %>
          <% end %>
        </li>
      </div>
      <div class='list'>
        <li>
          <div class="list-name">
            <%= link_to '公開中クエスト', '#'%>
          </div>
          未実装
        </li>
      </div>
      <div class='list'>
        <li>
          <div class="list-name">
            <%= link_to '一般依頼クエスト', '#'%>
          </div>
          未実装
        </li>
      </div>
    </div>
  </ul>
</div>

app/views/successes/new.html.erb
成功
<div class="success-form">
  <div><%= @quest.title%></div>
  <div><%= @quest.limit%></div>

  <%= form_with  model: @success,url: quest_successes_path, local: true do |f| %>
    <div class="failed-field">
      <div class="weight-bold-text">備考</div>
      <%= f.text_area :reason, class:"reason-text", id:"reasons-name", placeholder:"後で見返す用に、必要であれば利用してください(400文字)。",maxlength:"400" %>
      <%= f.submit "決定する" , class:"failed-btn" %>
      <%= link_to 'もどる', '/', class: "back-btn"%>
    </div>
  <% end %>
</div>